resolver: lts-7.3
packages:
- '.'
- '../dynamic-linker-template/'
extra-deps:
- c-storable-deriving-0.1.3
- dynamic-linker-template-0.1.1.0
- stm-linkedlist-0.1.0.0
- cabal-test-quickcheck-0.1.7
- diagrams-1.3.0.1
- pqueue-1.3.1.1

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "*": -fobject-code         # GHCI needs it because of the foreign primops
   "*": -freduction-depth=0   # used to allow compilation of large type-level Syscalls table

# system-ghc: true

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
